### ISSUE TITLE
Site is not loading

### ISSUE THREAD

**Issue by Skellingtor** [stephenou/fruitionsite#285]
Self-explanatory, the Notion page is not loading through my custom domain via Fruition. I'm not familiar with coding so I can't pinpoint the problem myself, but all I see is a white screen with an infinitely looping loading circle.

This is my domain: https://skellingtor.online/
This is the page it's supposed to point towards: https://skellingtor.notion.site/Hello-I-m-Matheus-Carneiro-d2e6bccc20e644bdacded2fa276f3b9c?pvs=4

**Comment by 09rd193** [comment]
I could not discover where the “endless loop” was occurring.

Temporarily, I replaced the worker code to redirect from my domain to “notion.site/” url.
Reference: "Redirect all requests to one URL
": https://developers.cloudflare.com/workers/examples/redirect/

My hypothesis is that it is related to the fact that Notion has started a service that allows users to set up their own domain name...

I will look into this a little more.
Hopefully someone with more knowledge will chime in.

**Comment by Skellingtor** [comment]
> I could not discover where the “endless loop” was occurring.
> 
> Temporarily, I replaced the worker code to redirect from my domain to “notion.site/” url. Reference: "Redirect all requests to one URL ": https://developers.cloudflare.com/workers/examples/redirect/
> 
> My hypothesis is that it is related to the fact that Notion has started a service that allows users to set up their own domain name...
> 
> I will look into this a little more. Hopefully someone with more knowledge will chime in.

Thank you, I'll use your solution as well until someone can figure this out

**Comment by timf34** [comment]
Yep I've encountered this problem since just yesterday as well, and have set up URL forwarding in the meantime. I'm also guessing Notion blocked this workaround to get people to use their paid custom domain hosting service. If anybody finds a way to make this work again, would appreciate it!

**Comment by 09rd193** [comment]
I finished fix worker.js by resolved bugs observed one by one.

I wish I could share it with PR, but I don't think it's the right way to fix it...
(since the past fixes also seemed to be one of the bugs...)

I can't PR(sorry), but I'll disclose the temp version if it's OK.
How about this way?

**Comment by 09rd193** [comment]
I will share my temp-fix code, use it if you like.
(Hope an expert will emerge...)

**▼ATTNTION: This code is unfinish fix provisional.▼**
<details>
<summary>temp-fix code</summary>

```js
  /* CONFIGURATION STARTS HERE */
  
  /* Step 1: enter your domain name like fruitionsite.com */
  const MY_DOMAIN = 'YOUR_DOMAIN';
  
  /*
   * Step 2: enter your URL slug to page ID mapping
   * The key on the left is the slug (without the slash)
   * The value on the right is the Notion page ID
   */
  const SLUG_TO_PAGE = {
    '': 'YOUR_SLUG_TO_PAGE',
  };
  
  /* Step 3: enter your page title and description for SEO purposes */
  const PAGE_TITLE = '';
  const PAGE_DESCRIPTION = '';
  
  /* Step 4: enter a Google Font name, you can choose from https://fonts.google.com */
  const GOOGLE_FONT = '';
  
  /* Step 5: enter any custom scripts you'd like */
  const CUSTOM_SCRIPT = ``;
  
  /* CONFIGURATION ENDS HERE */
  
  const PAGE_TO_SLUG = {};
  const slugs = [];
  const pages = [];
  Object.keys(SLUG_TO_PAGE).forEach(slug => {
    const page = SLUG_TO_PAGE[slug];
    slugs.push(slug);
    pages.push(page);
    PAGE_TO_SLUG[page] = slug;
  });
  
  addEventListener('fetch', event => {
    event.respondWith(fetchAndApply(event.request));
  });

  function generateSitemap() {
    let sitemap = '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">';
    slugs.forEach(
      (slug) =>
        (sitemap +=
          '<url><loc>https://' + MY_DOMAIN + '/' + slug + '</loc></url>')
    );
    sitemap += '</urlset>';
    return sitemap;
  }
  
  const corsHeaders = {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Methods': 'GET, HEAD, POST, PUT, OPTIONS',
    'Access-Control-Allow-Headers': 'Content-Type',
  };
  
  function handleOptions(request) {
    if (request.headers.get('Origin') !== null &&
      request.headers.get('Access-Control-Request-Method') !== null &&
      request.headers.get('Access-Control-Request-Headers') !== null) {
      // Handle CORS pre-flight request.
      return new Response(null, {
        headers: corsHeaders
      });
    } else {
      // Handle standard OPTIONS request.
      return new Response(null, {
        headers: {
          'Allow': 'GET, HEAD, POST, PUT, OPTIONS',
        }
      });
    }
  }
  
  async function fetchAndApply(request) {
    if (request.method === 'OPTIONS') {
      return handleOptions(request);
    }
    let url = new URL(request.url);
    url.hostname = 'www.notion.so';
    if (url.pathname === '/robots.txt') {
      return new Response('Sitemap: https://' + MY_DOMAIN + '/sitemap.xml');
    }
    if (url.pathname === '/sitemap.xml') {
      let response = new Response(generateSitemap());
      response.headers.set('content-type', 'application/xml');
      return response;
    }

    let response;
    if (url.pathname.startsWith('/app') && url.pathname.endsWith('js')) {
      response = await fetch(url.toString());
      let body = await response.text();
      response = new Response(body.replace(/www.notion.so/g, MY_DOMAIN).replace(/notion.so/g, MY_DOMAIN), response);
      response.headers.set('Content-Type', 'application/x-javascript');
      return response;
    } else if (url.pathname.startsWith('/api')) {
      // Forward API
      response = await fetch(url.toString(), {
        body: url.pathname.startsWith('/api/v3/getPublicPageData') ? null : request.body,
        headers: {
          'content-type': 'application/json;charset=UTF-8',
          'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36'
        },
        method: 'POST',
      });
      response = new Response(response.body, response);
      response.headers.set('Access-Control-Allow-Origin', '*');
      return response;
    } else if (slugs.indexOf(url.pathname.slice(1)) > -1) {
      const pageId = SLUG_TO_PAGE[url.pathname.slice(1)];
      const redirectUrl = 'https://' + MY_DOMAIN + '/' + pageId
      return Response.redirect(redirectUrl, 301);
    } else {
      response = await fetch(url.toString(), {
        body: request.body,
        headers: request.headers,
        method: request.method,
      });
      response = new Response(response.body, response);
      response.headers.delete('Content-Security-Policy');
      response.headers.delete('X-Content-Security-Policy');
    }  
    return appendJavascript(response, SLUG_TO_PAGE);
  }
  
  class MetaRewriter {
    element(element) {
      if (PAGE_TITLE !== '') {
        if (element.getAttribute('property') === 'og:title'
          || element.getAttribute('name') === 'twitter:title') {
          element.setAttribute('content', PAGE_TITLE);
        }
        if (element.tagName === 'title') {
          element.setInnerContent(PAGE_TITLE);
        }
      }
      if (PAGE_DESCRIPTION !== '') {
        if (element.getAttribute('name') === 'description'
          || element.getAttribute('property') === 'og:description'
          || element.getAttribute('name') === 'twitter:description') {
          element.setAttribute('content', PAGE_DESCRIPTION);
        }
      }
      if (element.getAttribute('property') === 'og:url'
        || element.getAttribute('name') === 'twitter:url') {
        element.setAttribute('content', MY_DOMAIN);
      }
      if (element.getAttribute('name') === 'apple-itunes-app') {
        element.remove();
      }
    }
  }
  
  class HeadRewriter {
    element(element) {
      /*
      if (GOOGLE_FONT !== '') {
        element.append(`<link href="https://fonts.googleapis.com/css?family=${GOOGLE_FONT.replace(' ', '+')}:Regular,Bold,Italic&display=swap" rel="stylesheet">
        <style>* { font-family: "${GOOGLE_FONT}" !important; }</style>`, {
          html: true
        });
      }
      */
      const el = `<style>
      div.notion-topbar > div > div:nth-child(1n).toggle-mode { display: block !important; }
      div.notion-topbar > div > div:nth-child(3) { display: none !important; }
      div.notion-topbar > div > div:nth-child(4) { display: none !important; }
      div.notion-topbar > div > div:nth-child(5) { display: none !important; }
      div.notion-topbar > div > div:nth-child(6) { display: none !important; }
      div.notion-topbar-mobile > div:nth-child(1n).toggle-mode { display: block !important; }
      div.notion-topbar-mobile > div:nth-child(3) { display: none !important; }
      div.notion-topbar-mobile > div:nth-child(4) { display: none !important; }
      div.notion-topbar-mobile > div:nth-child(5) { display: none !important; }
      </style>`.replace(/\r?\n/g, '');
      element.append(
        el, 
        {
          html: true
        }
      );
    }
  }
  
  class BodyRewriter {
    constructor(SLUG_TO_PAGE) {
      this.SLUG_TO_PAGE = SLUG_TO_PAGE;
    }
    element(element) {
      const el = `<script>
      window.CONFIG.domainBaseUrl = 'https://${MY_DOMAIN}';
      
      localStorage.__console = true;

      const SLUG_TO_PAGE = ${JSON.stringify(this.SLUG_TO_PAGE).replace(/"/g, '\'')};
      const PAGE_TO_SLUG = {};
      const slugs = [];
      const pages = [];
      const el = document.createElement('div');
      let redirected = false;
      Object.keys(SLUG_TO_PAGE).forEach(slug => {
        const page = SLUG_TO_PAGE[slug];
        slugs.push(slug);
        pages.push(page);
        PAGE_TO_SLUG[page] = slug;
      });
      function getPage() {
        return location.pathname.slice(-32);
      };
      function getSlug() {
        return location.pathname.slice(1);
      };
      function updateSlug() {
        const slug = PAGE_TO_SLUG[getPage()];
      };
      function onDark() {
      };
      function onLight() {
      };
      function toggle() {
        if (document.body.classList.contains('dark')) {
          onLight();
        } else {
          onDark();
        };
      };
      function addDarkModeButton(device) {
        const nav = device === 'web' ? document.querySelector('.notion-topbar').firstChild : document.querySelector('.notion-topbar-mobile');
        el.className = 'toggle-mode';
        el.addEventListener('click', toggle);
        nav.appendChild(el);
        onLight();
      };
      const observer = new MutationObserver(function() {
        if (redirected) return;
        const nav = document.querySelector('.notion-topbar');
        const mobileNav = document.querySelector('.notion-topbar-mobile');
        if (nav && nav.firstChild && nav.firstChild.firstChild
          || mobileNav && mobileNav.firstChild) {
          redirected = true;
          updateSlug();
          addDarkModeButton(nav ? 'web' : 'mobile');
          const onpopstate = window.onpopstate;
          window.onpopstate = function() {
            if (slugs.includes(getSlug())) {
              const page = SLUG_TO_PAGE[getSlug()];
              if (page) {
                history.replaceState(history.state, 'bypass', '/' + page);
              };
            };
            onpopstate.apply(this, [].slice.call(arguments));
            updateSlug();
          };
        };
      });
      observer.observe(document.querySelector('#notion-app'), {
        childList: true,
        subtree: true,
      });
      const replaceState = window.history.replaceState;
      window.history.replaceState = function(state) {
        if (arguments[1] !== 'bypass' && slugs.includes(getSlug())) return;
        return replaceState.apply(window.history, arguments);
      };
      const pushState = window.history.pushState;
      window.history.pushState = function(state) {
        const dest = new URL(location.protocol + location.host + arguments[2]);
        const id = dest.pathname.slice(-32);
        if (pages.includes(id)) {
          arguments[2] = '/' + PAGE_TO_SLUG[id];
        };
        return pushState.apply(window.history, arguments);
      };
      const open = window.XMLHttpRequest.prototype.open;
      window.XMLHttpRequest.prototype.open = function() {
        arguments[1] = arguments[1].replace('${MY_DOMAIN}', 'www.notion.so');
        return open.apply(this, [].slice.call(arguments));
      };
      </script>${CUSTOM_SCRIPT}`.replace(/\r?\n/g, '');

      element.append(
        el, 
        {html: true}
      );
    }
  }
  
  async function appendJavascript(res, SLUG_TO_PAGE) {
    return new HTMLRewriter()
      .on('title', new MetaRewriter())
      .on('meta', new MetaRewriter())
      .on('head', new HeadRewriter())
      .on('body', new BodyRewriter(SLUG_TO_PAGE))
      .transform(res);
  }
```
</details>

P.S. Please modify the YOUR_DOMAIN and YOUR_SLUG_TO_PAGE parts to your own settings.

**Comment by kanayankee** [comment]
@09rd193 
Hello! I encountered the same issue starting yesterday. I really appreciate you providing the updated code! If the pull request isn’t active, perhaps it might be worthwhile for someone in the community to create a new repository, like fruition-sync (given that the original code is under the MIT license…).

**Comment by kanayankee** [comment]
@09rd193 
Additionally, you might need to remove this part:

```javascript
if (element.tagName === 'title') {
  element.setInnerContent(PAGE_TITLE);
}
```

When previewing on an iPhone (or possibly all mobile devices?), it causes an error with Notion.

I’d really like to work alongside current Fruition users to help revive the Fruition service! 
Looking forward to collaborating with everyone. Thanks again for your support!

**Comment by 09rd193** [comment]
@kanayankee コメントありがとうございます！
I really really really think you are right.
I wish I could submit a PR or Fork in the correct procedure, but the reality is that I'm too busy...

> When previewing on an iPhone (or possibly all mobile devices?), it causes an error with Notion.

OMG... and Very nice pointed!
I checked in browser & iPhone.
I proceeded from the LOOP screen, satisfy, and stoped my hand.

**Comment by 09rd193** [comment]
@raznostoronniy 
Hello! Very very thanks for trying to deploy.

Deploy is successful on my site.
I have only changed MY_DOMAIN and SLUG_TO_PAGE from temp-fix.

Maybe my site is simple too far...
I will show though the online diff command results.
![image](https://github.com/user-attachments/assets/2036261d-83a6-49d4-b774-77e483eec8be)

**Comment by raznostoronniy** [comment]
> I will share my temp-fix code, use it if you like. (Hope an expert will emerge...)
> 
> **▼ATTNTION: This code is unfinish fix provisional.▼**
> 
> temp-fix code
> P.S. Please modify the YOUR_DOMAIN and YOUR_SLUG_TO_PAGE parts to your own settings.

Hi! Thanks for you attention to the issue! Is it work for you well?
I tried making the changes with your temp-fix, but the deploy fails with class HeadRewriter error.

**Comment by 09rd193** [comment]
@raznostoronniy 
Hello! Very very thanks for trying to deploy.

Deploy is successful on my site.
I have only changed MY_DOMAIN and SLUG_TO_PAGE from temp-fix.

Maybe my site is simple too far...
I will show though the online diff command results.
![image](https://github.com/user-attachments/assets/2036261d-83a6-49d4-b774-77e483eec8be)

**Comment by zhaotianjing** [comment]
Hi @09rd193 , I am unfamiliar with the worker code. To be better understood, in your case, you change "MY_DOMAIN" from `skellingtor.online` to `skellingtor.notion.site`, 
and change "SLUG_TO_PAGE" from `d2e6bccc20e644bdacded2fa276f3b9c?pvs=4` to `Hello-I-m-Matheus-Carneiro-d2e6bccc20e644bdacded2fa276f3b9c?pvs=4`?

Am I understanding your solution correctly? Thanks!

**Comment by TianHongZXY** [comment]
Thanks @09rd193 for your solution, after applying it my homepage works fine now. I have a question that the url displayed in the url bar is not `MY_DOMAIN` only, but with some suffix, e.g., my notion username and the notion page id, it looks like https://MY_DOMAIN/tianhongzxy/Xinyu-Zhu-2ab23fc3f366490ca6cefda66f4e61c8 , can we get the url displayed as `MY_DOMAIN` only?

**Comment by 09rd193** [comment]
@zhaotianjing 
Hi.
In my case setting use step 2 in site of https://stephenou.notion.site/Fruition-Free-Open-Source-Toolkit-for-Building-Websites-with-Notion-771ef38657244c27b9389734a9cbff44 .

Maybe your case...

0. Open ↑ page & find step 2 part
1. Input you own domain in "Your Domain" form.
2. Input your Notion site full url (ex: h/ttps://sample.notion.site/sample12345) in "Notion url ~" form
3. See code part under the "COPY THE CODE" button.
4. Copy & paest from Step 1 & Step2 part in code.

My announce be enough?
If insufficient explanation sorry may bad.

**Comment by Skellingtor** [comment]
This should go without saying but please don't use my domain for your sites, especially as you don't own it!

**Comment by 09rd193** [comment]
@TianHongZXY 
Thank you too.
Me too it was the same situation I had encountered.

To be honest, it is unresolved. Sorry!

The way I reproduce it is,

1. Open domain only url, it becomes a long URL.
2. Go to any page under the domain.
3. Click / Tap top left button in page, it becomes a domain-only URL  

(Why step 1 & 3 different URL...mystery now...)

Sorry I can't completely fix, as this is just a quick fix to get the screen to show up.

**Comment by zhaotianjing** [comment]
Hi @09rd193 

Thanks for your suggestion. I followed your instructions, and I found the worker code is exactly the same as my current worker code in Cloudflare. However, with the current worker code, my site is not loading. To use your code posted above, should I keep `MY_DOMAIN` and `SLUG_TO_PAGE` the same as before?

Thanks,

**Comment by 09rd193** [comment]
@Skellingtor I'm so sorry.
I quoted it because it was written in the comment.
I erase it soon.

**Comment by 09rd193** [comment]
Hi @zhaotianjing 
I think fine using previous MY_DOMAIN and SLUG_TO_PAGE.

And cross one's mind now...
Is it possible that it is working only in my worker and not in everyone?

**Comment by facundopadilla** [comment]
I have the same issue

**Comment by facundopadilla** [comment]
> I will share my temp-fix code, use it if you like. (Hope an expert will emerge...)
> 
> **▼ATTNTION: This code is unfinish fix provisional.▼**
> ...
> 
> P.S. Please modify the YOUR_DOMAIN and YOUR_SLUG_TO_PAGE parts to your own settings.

It´s works for me! thank you, in my PC with Opera and Chrome browser is ok, in my Samsung S24 Ultra working too

**Comment by facundopadilla** [comment]
In iPhone 15 Pro and 12 works too

**Comment by choirathome** [comment]
It is not working here too..

**Comment by 09rd193** [comment]
I'll think about whether to do "PR" or "fork" seriously...

**Comment by Mehul20** [comment]
Is anyone actively looking into this?

**Comment by zhaotianjing** [comment]
> Hi @zhaotianjing I think fine using previous MY_DOMAIN and SLUG_TO_PAGE.
> 
> And cross one's mind now... Is it possible that it is working only in my worker and not in everyone?

works for me for Chrome, Safari, iPhone, iPad. Thank you so much!

**Comment by bflack** [comment]
Ugh... unfortunately the fix here doesn't seem to work for my site. https://bestmadearchive.com if anyone cares to have a look.

I used the new code, and when it didn't work I also tried modifying the notion.so URLs to my personal notion URL (thiswholecity.notion.site), and also tried modifying the slug from just the 'code' bit to the full page name. Still not loading, still getting errors in the console but I'm not savvy enough to understand them or try to track them down.

**Comment by tdamsma** [comment]
After updating the code in this thread, which initially didn't resolve the issue, I proceeded to set:
  
    const PAGE_TITLE = '';
    const PAGE_DESCRIPTION = '';

Now, my site is functioning again.

**Comment by bflack** [comment]
> After updating the code in this thread, which initially didn't resolve the issue, I proceeded to set:
> 
> ```
> const PAGE_TITLE = '';
> const PAGE_DESCRIPTION = '';
> ```
> 
> Now, my site is functioning again.

That seemed to make the difference for me too.

**Comment by Mehul20** [comment]
> After updating the code in this thread, which initially didn't resolve the issue, I proceeded to set:
> 
> ```
> const PAGE_TITLE = '';
> const PAGE_DESCRIPTION = '';
> ```
> 
> Now, my site is functioning again.

This fixed for me too!

**Comment by Mehul20** [comment]
It's not working for me on **Iphone 16 though - Safari**

**Comment by zhaotianjing** [comment]
> @09rd193 Additionally, you might need to remove this part:
> 
> ```js
> if (element.tagName === 'title') {
>   element.setInnerContent(PAGE_TITLE);
> }
> ```
> 
> When previewing on an iPhone (or possibly all mobile devices?), it causes an error with Notion.
> 
> I’d really like to work alongside current Fruition users to help revive the Fruition service! Looking forward to collaborating with everyone. Thanks again for your support!

this makes the code work on my iPhone.

**Comment by disachantel** [comment]
> I will share my temp-fix code, use it if you like. (Hope an expert will emerge...)
> 
> **▼ATTNTION: This code is unfinish fix provisional.▼**
> 
> temp-fix code
> P.S. Please modify the YOUR_DOMAIN and YOUR_SLUG_TO_PAGE parts to your own settings.



> @09rd193 Additionally, you might need to remove this part:
> 
> ```js
> if (element.tagName === 'title') {
>   element.setInnerContent(PAGE_TITLE);
> }
> ```
> 
> When previewing on an iPhone (or possibly all mobile devices?), it causes an error with Notion.
> 
> I’d really like to work alongside current Fruition users to help revive the Fruition service! Looking forward to collaborating with everyone. Thanks again for your support!



> After updating the code in this thread, which initially didn't resolve the issue, I proceeded to set:
> 
> ```
> const PAGE_TITLE = '';
> const PAGE_DESCRIPTION = '';
> ```
> 
> Now, my site is functioning again.

just did all of the above and it's working for me again, BUT, the "pretty URLs" aren't rendering. 

instead, I see [mydomain.com/mynotionusername/longstringofcharactershere] like @09rd193 and @TianHongZXY have already noted.

has anyone found a fix for this?

EDIT (8 Nov): it has stopped working again.

**Comment by Quppi** [comment]
Even with all the suggestions here, it's still not working reliably for me. Somehow it works in Safari on mobile, but for example in Chrome on macOS it loads forever.
Does anyone have any idea what's going on there?

**Comment by choirathome** [comment]
It wasn't working here, but I changed the HTTPS to HTTP and it worked. It redirects to the notion.sites page, the pretty link doesn't shows and the layout is the same as the notion pages: not the fruition layout with the dark mode button that doesn't work and everything else. It is better than an error, but it is a kind of redirection. Hope someone figure out a better solution.

**Comment by choirathome** [comment]
> It wasn't working here, but I changed the HTTPS to HTTP and it worked. It redirects to the notion.sites page, the pretty link doesn't shows and the layout is the same as the notion pages: not the fruition layout with the dark mode button that doesn't work and everything else. It is better than an error, but it is a kind of redirection. Hope someone figure out a better solution.

Now it is working with HTTPS. I think it is something related to the cloudflare servers. Just a matter of time to implement the securities, I think..

**Comment by raimbetov** [comment]
Not working for me on a desktop (Firefox). Works on Android (Chrome).

**Comment by Dminus251** [comment]
> Not working for me on a desktop (Firefox). Works on Android (Chrome).

Same. only works on Android Chrome, not on desktop or other browser.

**Comment by 09rd193** [comment]
Thank you everyone for sharing the many bug.
I don't know now if I can fix bugs, but I will try to fix it.
(I have not give up yet.)

Problems
- longer URL (URLs are longer than before.)
- Not working, case of write at TITLE / DISCRIPTION (Maybe can see on desktop, but not on mobile.)

Was there anything else?

**Comment by facundopadilla** [comment]
I'm here again, the site is not working again 😔

**Comment by 09rd193** [comment]
Compared done many working fork codes.

Modified the temp-fix code i wrote before.
Could you please confirm it?

- I think the url is shorter now.
- I think it now works on both Desktop / Mobile even if you enter TITLE / DISCRIPTION.

**▼ATTNTION: This code is unfinish fix provisional.▼**
<details>
<summary>temp-fix code</summary>

```js
/* CONFIGURATION STARTS HERE */

/* Step 1: enter your domain name like fruitionsite.com */
const MY_DOMAIN = 'YOUR_DOMAIN';

/*
 * Step 2: enter your URL slug to page ID mapping
 * The key on the left is the slug (without the slash)
 * The value on the right is the Notion page ID
 */
const SLUG_TO_PAGE = {
  '': 'YOUR_SLUG_TO_PAGE',
};

/* Step 3: enter your page title and description for SEO purposes */
const PAGE_TITLE = '';
const PAGE_DESCRIPTION = '';

/* Step 4: enter a Google Font name, you can choose from https://fonts.google.com */
const GOOGLE_FONT = '';

/* Step 5: enter any custom scripts you'd like */
const CUSTOM_SCRIPT = ``;

/* CONFIGURATION ENDS HERE */

const PAGE_TO_SLUG = {};
const slugs = [];
const pages = [];
Object.keys(SLUG_TO_PAGE).forEach(slug => {
  const page = SLUG_TO_PAGE[slug];
  slugs.push(slug);
  pages.push(page);
  PAGE_TO_SLUG[page] = slug;
});

addEventListener('fetch', event => {
  event.respondWith(fetchAndApply(event.request));
});

function generateSitemap() {
  let sitemap = '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">';
  slugs.forEach(
    (slug) => (sitemap += '<url><loc>https://' + MY_DOMAIN + '/' + slug + '</loc></url>')
  );
  sitemap += '</urlset>';
  return sitemap;
}

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET, HEAD, POST, PUT, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type',
};

function handleOptions(request) {
  if (request.headers.get('Origin') !== null &&
    request.headers.get('Access-Control-Request-Method') !== null &&
    request.headers.get('Access-Control-Request-Headers') !== null) {
    // Handle CORS pre-flight request.
    return new Response(null, {
      headers: corsHeaders
    });
  } else {
    // Handle standard OPTIONS request.
    return new Response(null, {
      headers: {
        'Allow': 'GET, HEAD, POST, PUT, OPTIONS',
      }
    });
  }
}

async function fetchAndApply(request) {
  if (request.method === 'OPTIONS') {
    return handleOptions(request);
  }
  let url = new URL(request.url);
  url.hostname = 'www.notion.so';
  if (url.pathname === '/robots.txt') {
    return new Response('Sitemap: https://' + MY_DOMAIN + '/sitemap.xml');
  }
  if (url.pathname === '/sitemap.xml') {
    let response = new Response(generateSitemap());
    response.headers.set('content-type', 'application/xml');
    return response;
  }
  let response;
  if (url.pathname.startsWith('/app') && url.pathname.endsWith('js')) {
    response = await fetch(url.toString());
    let body = await response.text();
    response = new Response(body.replace(/www.notion.so/g, MY_DOMAIN).replace(/notion.so/g, MY_DOMAIN), response);
    response.headers.set('Content-Type', 'application/x-javascript');
    return response;
  } else if (url.pathname.startsWith('/api')) {
    // Forward API
    response = await fetch(url.toString(), {
      body: url.pathname.startsWith('/api/v3/getPublicPageData') ? null : request.body,
      headers: {
        'content-type': 'application/json;charset=UTF-8',
        'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36'
      },
      method: 'POST'
    });
    response = new Response(response.body, response);
    response.headers.set('Access-Control-Allow-Origin', '*');
    return response;
  } else if (url.pathname.endsWith('.js')){
    response = await fetch(url.toString());
    let body = await response.text();
    response = new Response(
      body,
      response
    );
    response.headers.set('Content-Type', 'application/x-javascript');
    return response;
  } else if (slugs.indexOf(url.pathname.slice(1)) > -1) {
    const pageId = SLUG_TO_PAGE[url.pathname.slice(1)];
    return Response.redirect('https://' + MY_DOMAIN + '/' + pageId, 301);
  } else if ( pages.indexOf(url.pathname.slice(1)) === -1 &&
              url.pathname.slice(1).match(/[0-9a-f]{32}/)
  ) {
    return Response.redirect('https://' + MY_DOMAIN, 301);
  }
  
  else {
    response = await fetch(url.toString(), {
      body: request.body,
      headers: request.headers,
      method: request.method
    });
    response = new Response(response.body, response);
    response.headers.delete('Content-Security-Policy');
    response.headers.delete('X-Content-Security-Policy');
  }

  return appendJavascript(response, SLUG_TO_PAGE);
}

class MetaRewriter {
  element(element) {
    // @ts-ignore
    if (PAGE_TITLE !== '') {
      if (
        element.getAttribute('property') === 'og:title' ||
        element.getAttribute('name') === 'twitter:title'
      ) {
        element.setAttribute('content', PAGE_TITLE);
      }
      if (element.tagName === 'title') {
        element.setInnerContent(PAGE_TITLE);
      }
    }
    // @ts-ignore
    if (PAGE_DESCRIPTION !== '') {
      if (
        element.getAttribute('name') === 'description' ||
        element.getAttribute('property') === 'og:description' ||
        element.getAttribute('name') === 'twitter:description'
      ) {
        element.setAttribute('content', PAGE_DESCRIPTION);
      }
    }
    if (
      element.getAttribute('property') === 'og:url' ||
      element.getAttribute('name') === 'twitter:url'
    ) {
      element.setAttribute('content', MY_DOMAIN);
    }
    if (element.getAttribute('name') === 'apple-itunes-app') {
      element.remove();
    }
  }
}

class HeadRewriter {
  element(element) {
    if (GOOGLE_FONT !== "") {
      element.append(
        // @ts-ignore
        `<link href='https://fonts.googleapis.com/css?family=${GOOGLE_FONT.replace(' ', '+')}:Regular,Bold,Italic&display=swap' rel='stylesheet'>
        <style>* { font-family: "${GOOGLE_FONT}" !important; }</style>`,
        {
          html: true
        }
      );
    }
    element.append(
      `<style>
      div.notion-topbar > div > div:nth-child(1n).toggle-mode { display: none !important; }
      div.notion-topbar > div > div:nth-child(3) { display: none !important; }
      div.notion-topbar > div > div:nth-child(4) { display: none !important; }
      div.notion-topbar > div > div:nth-child(5) { display: none !important; }
      div.notion-topbar > div > div:nth-child(6) { display: none !important; }
      div.notion-topbar-mobile > div:nth-child(1n).toggle-mode { display: none !important; }
      div.notion-topbar-mobile > div:nth-child(3) { display: none !important; }
      div.notion-topbar-mobile > div:nth-child(4) { display: none !important; }
      div.notion-topbar-mobile > div:nth-child(5) { display: none !important; }
      </style>`,
      {
        html: true
      }
    );
  }
}

class BodyRewriter {
  constructor(SLUG_TO_PAGE) {
    this.SLUG_TO_PAGE = SLUG_TO_PAGE;
  }
  element(element) {
    element.append(
      `<script>
      window.CONFIG.domainBaseUrl = 'https://${MY_DOMAIN}';
      localStorage.__console = true;
      const SLUG_TO_PAGE = ${JSON.stringify(this.SLUG_TO_PAGE)};
      const PAGE_TO_SLUG = {};
      const slugs = [];
      const pages = [];
      const el = document.createElement('div');
      let redirected = false;
      Object.keys(SLUG_TO_PAGE).forEach(slug => {
        const page = SLUG_TO_PAGE[slug];
        slugs.push(slug);
        pages.push(page);
        PAGE_TO_SLUG[page] = slug;
      });
      function getPage() {
        return location.pathname.slice(-32);
      }
      function getSlug() {
        return location.pathname.slice(1);
      }
      function updateSlug() {
        const slug = PAGE_TO_SLUG[getPage()];
        if (slug != null) {
          history.replaceState(history.state, '', '/' + slug);
        }
      }
      function onDark() {
        el.innerHTML = '<div title="Change to Light Mode" style="margin-left: auto; margin-right: 14px; min-width: 0px;"><div role="button" tabindex="0" style="user-select: none; transition: background 120ms ease-in 0s; cursor: pointer; border-radius: 44px;"><div style="display: flex; flex-shrink: 0; height: 14px; width: 26px; border-radius: 44px; padding: 2px; box-sizing: content-box; background: rgb(46, 170, 220); transition: background 200ms ease 0s, box-shadow 200ms ease 0s;"><div style="width: 14px; height: 14px; border-radius: 44px; background: white; transition: transform 200ms ease-out 0s, background 200ms ease-out 0s; transform: translateX(12px) translateY(0px);"></div></div></div></div>';
        document.body.classList.add('dark');
        __console.environment.ThemeStore.setState({ mode: 'dark' });
      };
      function onLight() {
        el.innerHTML = '<div title="Change to Dark Mode" style="margin-left: auto; margin-right: 14px; min-width: 0px;"><div role="button" tabindex="0" style="user-select: none; transition: background 120ms ease-in 0s; cursor: pointer; border-radius: 44px;"><div style="display: flex; flex-shrink: 0; height: 14px; width: 26px; border-radius: 44px; padding: 2px; box-sizing: content-box; background: rgba(135, 131, 120, 0.3); transition: background 200ms ease 0s, box-shadow 200ms ease 0s;"><div style="width: 14px; height: 14px; border-radius: 44px; background: white; transition: transform 200ms ease-out 0s, background 200ms ease-out 0s; transform: translateX(0px) translateY(0px);"></div></div></div></div>';
        document.body.classList.remove('dark');
        __console.environment.ThemeStore.setState({ mode: 'light' });
      }
      function toggle() {
        if (document.body.classList.contains('dark')) {
          onLight();
        } else {
          onDark();
        }
      }
      function addDarkModeButton(device) {
        const nav = device === 'web' ? document.querySelector('.notion-topbar').firstChild : document.querySelector('.notion-topbar-mobile');
        el.className = 'toggle-mode';
        el.addEventListener('click', toggle);
        nav.appendChild(el);

        // enable smart dark mode based on user-preference
        if (window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches) {
            onDark();
        } else {
            onLight();
        }

        // try to detect if user-preference change
        window.matchMedia('(prefers-color-scheme: dark)').addEventListener('change', e => {
            toggle();
        });
      }
      const observer = new MutationObserver(function() {
        if (redirected) return;
        const nav = document.querySelector('.notion-topbar');
        const mobileNav = document.querySelector('.notion-topbar-mobile');
        if (nav && nav.firstChild && nav.firstChild.firstChild
          || mobileNav && mobileNav.firstChild) {
          redirected = true;
          updateSlug();
          addDarkModeButton(nav ? 'web' : 'mobile');
          const onpopstate = window.onpopstate;
          window.onpopstate = function() {
            if (slugs.includes(getSlug())) {
              const page = SLUG_TO_PAGE[getSlug()];
              if (page) {
                history.replaceState(history.state, 'bypass', '/' + page);
              }
            }
            onpopstate.apply(this, [].slice.call(arguments));
            updateSlug();
          };
        }
      });
      observer.observe(document.querySelector('#notion-app'), {
        childList: true,
        subtree: true,
      });
      const replaceState = window.history.replaceState;
      window.history.replaceState = function(state) {
        if (arguments[1] !== 'bypass' && slugs.includes(getSlug())) return;
        return replaceState.apply(window.history, arguments);
      };
      const pushState = window.history.pushState;
      window.history.pushState = function(state) {
        const dest = new URL(location.protocol + location.host + arguments[2]);
        const id = dest.pathname.slice(-32);
        if (pages.includes(id)) {
          arguments[2] = '/' + PAGE_TO_SLUG[id];
        }
        return pushState.apply(window.history, arguments);
      };
      const open = window.XMLHttpRequest.prototype.open;
      window.XMLHttpRequest.prototype.open = function() {
        arguments[1] = arguments[1].replace('${MY_DOMAIN}', 'www.notion.so');
        return open.apply(this, [].slice.call(arguments));
      };
    </script>${CUSTOM_SCRIPT}`,
      {
        html: true
      }
    );
  }
}

async function appendJavascript(res, SLUG_TO_PAGE) {
  return new HTMLRewriter()
    .on('title', new MetaRewriter())
    .on('meta', new MetaRewriter())
    .on('head', new HeadRewriter())
    .on('body', new BodyRewriter(SLUG_TO_PAGE))
    .transform(res);
}
```
</details>

P.S. But, back button problem may have reappeared.

**Comment by vorn0** [comment]
> Compared done many working fork codes.
> 
> Modified the temp-fix code i wrote before. Could you please confirm it?
> 
> * I think the url is shorter now.
> * I think it now works on both Desktop / Mobile even if you enter TITLE / DISCRIPTION.
> 
> **▼ATTNTION: This code is unfinish fix provisional.▼**
> 
> temp-fix code

Short link fixed with this, thank you!
One of my sites loads on mobile but not on desktop Chrome. Yet it loads fine in incognito..

**Comment by Dminus251** [comment]
> Compared done many working fork codes.
> 
> Modified the temp-fix code i wrote before. Could you please confirm it?
> 
> * I think the url is shorter now.
> * I think it now works on both Desktop / Mobile even if you enter TITLE / DISCRIPTION.
> 
> **▼ATTNTION: This code is unfinish fix provisional.▼**
> 
> temp-fix code
> P.S. But, back button problem may have reappeared.

Your temp-fix code correctly works for me using PC, mobile Chrome. (I removed cookie in my PC Chrome.)
~~And I found that the error persists when using samsung internet browser in mobile.~~
I'm sorry. after removing cookie in samsung internet browser, The code correctly works.

thank you for your action.

**Comment by 09rd193** [comment]
@vorn0 

> One of my sites loads on mobile but not on desktop Chrome. Yet it loads fine in incognito..

If desktop, why don't you clear browser's cache before visiting your site?
Would there be any change?

**Comment by gth001** [comment]
Thank you. That code fixed my website. Pressing back leads to notion login page but I can ignore that bug - much better than nothing loading. https://github.com/stephenou/fruitionsite/issues/285#issuecomment-2466529068

**Comment by LifeofDan-EL** [comment]
> Compared done many working fork codes.
> 
> Modified the temp-fix code i wrote before. Could you please confirm it?
> 
> * I think the url is shorter now.
> * I think it now works on both Desktop / Mobile even if you enter TITLE / DISCRIPTION.
> 
> **▼ATTNTION: This code is unfinish fix provisional.▼**
> 
> temp-fix code
> P.S. But, back button problem may have reappeared.


Thanks for this, I just used it and it works on my Brave desktop browser and on my Android Chrome browser. I had to clear the cache.

**Comment by Vietnq99** [comment]
> Compared done many working fork codes.
> 
> Modified the temp-fix code i wrote before. Could you please confirm it?
> 
> * I think the url is shorter now.
> * I think it now works on both Desktop / Mobile even if you enter TITLE / DISCRIPTION.
> 
> **▼ATTNTION: This code is unfinish fix provisional.▼**
> 
> temp-fix code
> P.S. But, back button problem may have reappeared.

Thank you! It's working for me

**Comment by lousykids** [comment]
> Compared done many working fork codes.
> 
> Modified the temp-fix code i wrote before. Could you please confirm it?
> 
> * I think the url is shorter now.
> * I think it now works on both Desktop / Mobile even if you enter TITLE / DISCRIPTION.
> 
> **▼ATTNTION: This code is unfinish fix provisional.▼**
> 
> temp-fix code
> P.S. But, back button problem may have reappeared.


This worked great! 

But, when using a url link to a sub-page, it just re-directs back to the main domain url. So from inside the website the pages work, but url links to sub-pages do not work, they take you to the main domain url page. 

Anyone else having this issue? Any help?

and since we are here, could we talk about custom favicon?

**Comment by lousykids** [comment]
> > Compared done many working fork codes.
> 
> > 
> 
> > Modified the temp-fix code i wrote before. Could you please confirm it?
> 
> > 
> 
> > * I think the url is shorter now.
> 
> > * I think it now works on both Desktop / Mobile even if you enter TITLE / DISCRIPTION.
> 
> > 
> 
> > **▼ATTNTION: This code is unfinish fix provisional.▼**
> 
> > 
> 
> > temp-fix code
> 
> > P.S. But, back button problem may have reappeared.
> 
> 
> 
> 
> 
> This worked great! 
> 
> 
> 
> But, when using a url link to a sub-page, it just re-directs back to the main domain url. So from inside the website the pages work, but url links to sub-pages do not work, they take you to the main domain url page. 
> 
> 
> 
> Anyone else having this issue? Any help?
> 
> 
> 
> and since we are here, could we talk about custom favicon?

Doesn't work again... We need somebody white can create a real working option! Who knows the code.

**Comment by lousykids** [comment]
> > Compared done many working fork codes.
> 
> > 
> 
> > Modified the temp-fix code i wrote before. Could you please confirm it?
> 
> > 
> 
> > * I think the url is shorter now.
> 
> > * I think it now works on both Desktop / Mobile even if you enter TITLE / DISCRIPTION.
> 
> > 
> 
> > **▼ATTNTION: This code is unfinish fix provisional.▼**
> 
> > 
> 
> > temp-fix code
> 
> > P.S. But, back button problem may have reappeared.
> 
> 
> 
> 
> 
> This worked great! 
> 
> 
> 
> But, when using a url link to a sub-page, it just re-directs back to the main domain url. So from inside the website the pages work, but url links to sub-pages do not work, they take you to the main domain url page. 
> 
> 
> 
> Anyone else having this issue? Any help?
> 
> 
> 
> and since we are here, could we talk about custom favicon?

Doesn't work again... We need someone who can create a working option. Who knows the code.

**Comment by vorn0** [comment]
Earlier today I was getting this:
**'This page has been flagged as unsafe
This page may contain spam, phishing, illegal, or inappropriate content. If you received this link from an unknown source, we suggest you to close this tab. Proceed anyway?'**
Now I'm just getting **'This content does not exist'**

My second site using the same code works as normal...for now.

**Comment by facundopadilla** [comment]
My site works again, tested in:
- Mac Sequoia with Chrome and Safari ✅ 
- Android (S24 Ultra) with Chrome ✅

**Comment by alekqss** [comment]
> > Compared done many working fork codes.
> > Modified the temp-fix code i wrote before. Could you please confirm it?
> > 
> > * I think the url is shorter now.
> > * I think it now works on both Desktop / Mobile even if you enter TITLE / DISCRIPTION.
> > 
> > **▼ATTNTION: This code is unfinish fix provisional.▼**
> > temp-fix code
> > P.S. But, back button problem may have reappeared.
> 
> This worked great!
> 
> But, when using a url link to a sub-page, it just re-directs back to the main domain url. So from inside the website the pages work, but url links to sub-pages do not work, they take you to the main domain url page.
> 
> Anyone else having this issue? Any help?
> 
> and since we are here, could we talk about custom favicon?

Exact same issue here. None of the links to subpages I created with bit.ly works. Not even direct links to the notion subpage. It redirects to the main domain page.

**Comment by 09rd193** [comment]
I was trying to fix the “bug where pressing back brings up the login page”.

I would like to set the favicon too, but it's not a fatal bug, so I've been putting it off.
(I know of a wicked way to set it up, but I don't recommend it)

P.S. I apologize for two points. I haven't been able to find the time to fix it, and the possible weird text in the DeepL translation.

**Comment by alekqss** [comment]
> > > Compared done many working fork codes.
> > > Modified the temp-fix code i wrote before. Could you please confirm it?
> > > 
> > > * I think the url is shorter now.
> > > * I think it now works on both Desktop / Mobile even if you enter TITLE / DISCRIPTION.
> > > 
> > > **▼ATTNTION: This code is unfinish fix provisional.▼**
> > > temp-fix code
> > > P.S. But, back button problem may have reappeared.
> > 
> > 
> > This worked great!
> > But, when using a url link to a sub-page, it just re-directs back to the main domain url. So from inside the website the pages work, but url links to sub-pages do not work, they take you to the main domain url page.
> > Anyone else having this issue? Any help?
> > and since we are here, could we talk about custom favicon?
> 
> Exact same issue here. None of the links to subpages I created with bit.ly works. Not even direct links to the notion subpage. It redirects to the main domain page.

Any workaround to solve this would be much appreciated

**Comment by 09rd193** [comment]
I have tried various modif, but feel it will be difficult to make it better now.

Apologize if anyone has any expectations...

**Comment by TianHongZXY** [comment]
Thanks a lot for your effort and time, I really appreciate it! @09rd193

**Comment by pcperini** [comment]
Posting for posterity.

Tried all of these fixes and couldn't get mine working. My needs are a bit less complex than the full Fruition feature set, so I just reimplemented it via a reverse proxy. https://gist.github.com/pcperini/62fd061d4cc3f6c3bea94e80f4bc3613
